//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppMovilEscuela.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWebEscuelaSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioWebEscuela : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GuardarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarrUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarAlumnosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarAlumnosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarSintomasOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarHijosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarSintomasOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback NombreAlumnosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioWebEscuela() {
            this.Url = "http://192.168.0.12:82/ServicioWebEscuela.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GuardarUsuariosCompletedEventHandler GuardarUsuariosCompleted;
        
        /// <remarks/>
        public event MostrarUsuariosCompletedEventHandler MostrarUsuariosCompleted;
        
        /// <remarks/>
        public event BuscarrUsuariosCompletedEventHandler BuscarrUsuariosCompleted;
        
        /// <remarks/>
        public event MostrarAlumnosCompletedEventHandler MostrarAlumnosCompleted;
        
        /// <remarks/>
        public event BuscarAlumnosCompletedEventHandler BuscarAlumnosCompleted;
        
        /// <remarks/>
        public event MostrarSintomasCompletedEventHandler MostrarSintomasCompleted;
        
        /// <remarks/>
        public event MostrarHijosCompletedEventHandler MostrarHijosCompleted;
        
        /// <remarks/>
        public event GuardarAlumnoCompletedEventHandler GuardarAlumnoCompleted;
        
        /// <remarks/>
        public event GuardarSintomasCompletedEventHandler GuardarSintomasCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event NombreAlumnosCompletedEventHandler NombreAlumnosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarUsuarios(string Nombre, string AP, string AM, string Usuario, string Contraseña) {
            object[] results = this.Invoke("GuardarUsuarios", new object[] {
                        Nombre,
                        AP,
                        AM,
                        Usuario,
                        Contraseña});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarUsuariosAsync(string Nombre, string AP, string AM, string Usuario, string Contraseña) {
            this.GuardarUsuariosAsync(Nombre, AP, AM, Usuario, Contraseña, null);
        }
        
        /// <remarks/>
        public void GuardarUsuariosAsync(string Nombre, string AP, string AM, string Usuario, string Contraseña, object userState) {
            if ((this.GuardarUsuariosOperationCompleted == null)) {
                this.GuardarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarUsuariosOperationCompleted);
            }
            this.InvokeAsync("GuardarUsuarios", new object[] {
                        Nombre,
                        AP,
                        AM,
                        Usuario,
                        Contraseña}, this.GuardarUsuariosOperationCompleted, userState);
        }
        
        private void OnGuardarUsuariosOperationCompleted(object arg) {
            if ((this.GuardarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarUsuariosCompleted(this, new GuardarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MostrarUsuarios() {
            object[] results = this.Invoke("MostrarUsuarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarUsuariosAsync() {
            this.MostrarUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void MostrarUsuariosAsync(object userState) {
            if ((this.MostrarUsuariosOperationCompleted == null)) {
                this.MostrarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarUsuariosOperationCompleted);
            }
            this.InvokeAsync("MostrarUsuarios", new object[0], this.MostrarUsuariosOperationCompleted, userState);
        }
        
        private void OnMostrarUsuariosOperationCompleted(object arg) {
            if ((this.MostrarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarUsuariosCompleted(this, new MostrarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarrUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarrUsuarios(string usuario) {
            object[] results = this.Invoke("BuscarrUsuarios", new object[] {
                        usuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarrUsuariosAsync(string usuario) {
            this.BuscarrUsuariosAsync(usuario, null);
        }
        
        /// <remarks/>
        public void BuscarrUsuariosAsync(string usuario, object userState) {
            if ((this.BuscarrUsuariosOperationCompleted == null)) {
                this.BuscarrUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarrUsuariosOperationCompleted);
            }
            this.InvokeAsync("BuscarrUsuarios", new object[] {
                        usuario}, this.BuscarrUsuariosOperationCompleted, userState);
        }
        
        private void OnBuscarrUsuariosOperationCompleted(object arg) {
            if ((this.BuscarrUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarrUsuariosCompleted(this, new BuscarrUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarAlumnos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MostrarAlumnos() {
            object[] results = this.Invoke("MostrarAlumnos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarAlumnosAsync() {
            this.MostrarAlumnosAsync(null);
        }
        
        /// <remarks/>
        public void MostrarAlumnosAsync(object userState) {
            if ((this.MostrarAlumnosOperationCompleted == null)) {
                this.MostrarAlumnosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarAlumnosOperationCompleted);
            }
            this.InvokeAsync("MostrarAlumnos", new object[0], this.MostrarAlumnosOperationCompleted, userState);
        }
        
        private void OnMostrarAlumnosOperationCompleted(object arg) {
            if ((this.MostrarAlumnosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarAlumnosCompleted(this, new MostrarAlumnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarAlumnos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarAlumnos(string Matricula) {
            object[] results = this.Invoke("BuscarAlumnos", new object[] {
                        Matricula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAlumnosAsync(string Matricula) {
            this.BuscarAlumnosAsync(Matricula, null);
        }
        
        /// <remarks/>
        public void BuscarAlumnosAsync(string Matricula, object userState) {
            if ((this.BuscarAlumnosOperationCompleted == null)) {
                this.BuscarAlumnosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAlumnosOperationCompleted);
            }
            this.InvokeAsync("BuscarAlumnos", new object[] {
                        Matricula}, this.BuscarAlumnosOperationCompleted, userState);
        }
        
        private void OnBuscarAlumnosOperationCompleted(object arg) {
            if ((this.BuscarAlumnosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAlumnosCompleted(this, new BuscarAlumnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarSintomas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MostrarSintomas(string Fecha, string Sintomas, string Asiste, string Matricula) {
            object[] results = this.Invoke("MostrarSintomas", new object[] {
                        Fecha,
                        Sintomas,
                        Asiste,
                        Matricula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarSintomasAsync(string Fecha, string Sintomas, string Asiste, string Matricula) {
            this.MostrarSintomasAsync(Fecha, Sintomas, Asiste, Matricula, null);
        }
        
        /// <remarks/>
        public void MostrarSintomasAsync(string Fecha, string Sintomas, string Asiste, string Matricula, object userState) {
            if ((this.MostrarSintomasOperationCompleted == null)) {
                this.MostrarSintomasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarSintomasOperationCompleted);
            }
            this.InvokeAsync("MostrarSintomas", new object[] {
                        Fecha,
                        Sintomas,
                        Asiste,
                        Matricula}, this.MostrarSintomasOperationCompleted, userState);
        }
        
        private void OnMostrarSintomasOperationCompleted(object arg) {
            if ((this.MostrarSintomasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarSintomasCompleted(this, new MostrarSintomasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarHijos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MostrarHijos(int id) {
            object[] results = this.Invoke("MostrarHijos", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarHijosAsync(int id) {
            this.MostrarHijosAsync(id, null);
        }
        
        /// <remarks/>
        public void MostrarHijosAsync(int id, object userState) {
            if ((this.MostrarHijosOperationCompleted == null)) {
                this.MostrarHijosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarHijosOperationCompleted);
            }
            this.InvokeAsync("MostrarHijos", new object[] {
                        id}, this.MostrarHijosOperationCompleted, userState);
        }
        
        private void OnMostrarHijosOperationCompleted(object arg) {
            if ((this.MostrarHijosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarHijosCompleted(this, new MostrarHijosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarAlumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarAlumno(string Matricula, string Nombre, string AP, string AM, string Grado, string Grupo, int edad, int FkUsuario) {
            object[] results = this.Invoke("GuardarAlumno", new object[] {
                        Matricula,
                        Nombre,
                        AP,
                        AM,
                        Grado,
                        Grupo,
                        edad,
                        FkUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAlumnoAsync(string Matricula, string Nombre, string AP, string AM, string Grado, string Grupo, int edad, int FkUsuario) {
            this.GuardarAlumnoAsync(Matricula, Nombre, AP, AM, Grado, Grupo, edad, FkUsuario, null);
        }
        
        /// <remarks/>
        public void GuardarAlumnoAsync(string Matricula, string Nombre, string AP, string AM, string Grado, string Grupo, int edad, int FkUsuario, object userState) {
            if ((this.GuardarAlumnoOperationCompleted == null)) {
                this.GuardarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarAlumnoOperationCompleted);
            }
            this.InvokeAsync("GuardarAlumno", new object[] {
                        Matricula,
                        Nombre,
                        AP,
                        AM,
                        Grado,
                        Grupo,
                        edad,
                        FkUsuario}, this.GuardarAlumnoOperationCompleted, userState);
        }
        
        private void OnGuardarAlumnoOperationCompleted(object arg) {
            if ((this.GuardarAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarAlumnoCompleted(this, new GuardarAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarSintomas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarSintomas(string FkAlumno, double temp, string Sintomas, string observaciones, string Asistenacia) {
            object[] results = this.Invoke("GuardarSintomas", new object[] {
                        FkAlumno,
                        temp,
                        Sintomas,
                        observaciones,
                        Asistenacia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarSintomasAsync(string FkAlumno, double temp, string Sintomas, string observaciones, string Asistenacia) {
            this.GuardarSintomasAsync(FkAlumno, temp, Sintomas, observaciones, Asistenacia, null);
        }
        
        /// <remarks/>
        public void GuardarSintomasAsync(string FkAlumno, double temp, string Sintomas, string observaciones, string Asistenacia, object userState) {
            if ((this.GuardarSintomasOperationCompleted == null)) {
                this.GuardarSintomasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarSintomasOperationCompleted);
            }
            this.InvokeAsync("GuardarSintomas", new object[] {
                        FkAlumno,
                        temp,
                        Sintomas,
                        observaciones,
                        Asistenacia}, this.GuardarSintomasOperationCompleted, userState);
        }
        
        private void OnGuardarSintomasOperationCompleted(object arg) {
            if ((this.GuardarSintomasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarSintomasCompleted(this, new GuardarSintomasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Login() {
            object[] results = this.Invoke("Login", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync() {
            this.LoginAsync(null);
        }
        
        /// <remarks/>
        public void LoginAsync(object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[0], this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NombreAlumnos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet NombreAlumnos(int Fkusuario) {
            object[] results = this.Invoke("NombreAlumnos", new object[] {
                        Fkusuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void NombreAlumnosAsync(int Fkusuario) {
            this.NombreAlumnosAsync(Fkusuario, null);
        }
        
        /// <remarks/>
        public void NombreAlumnosAsync(int Fkusuario, object userState) {
            if ((this.NombreAlumnosOperationCompleted == null)) {
                this.NombreAlumnosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNombreAlumnosOperationCompleted);
            }
            this.InvokeAsync("NombreAlumnos", new object[] {
                        Fkusuario}, this.NombreAlumnosOperationCompleted, userState);
        }
        
        private void OnNombreAlumnosOperationCompleted(object arg) {
            if ((this.NombreAlumnosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NombreAlumnosCompleted(this, new NombreAlumnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarUsuariosCompletedEventHandler(object sender, GuardarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MostrarUsuariosCompletedEventHandler(object sender, MostrarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarrUsuariosCompletedEventHandler(object sender, BuscarrUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarrUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarrUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MostrarAlumnosCompletedEventHandler(object sender, MostrarAlumnosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarAlumnosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarAlumnosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarAlumnosCompletedEventHandler(object sender, BuscarAlumnosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAlumnosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarAlumnosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MostrarSintomasCompletedEventHandler(object sender, MostrarSintomasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarSintomasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarSintomasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MostrarHijosCompletedEventHandler(object sender, MostrarHijosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarHijosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarHijosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarAlumnoCompletedEventHandler(object sender, GuardarAlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarSintomasCompletedEventHandler(object sender, GuardarSintomasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarSintomasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarSintomasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void NombreAlumnosCompletedEventHandler(object sender, NombreAlumnosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NombreAlumnosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NombreAlumnosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591